version: '3'

tasks:
  build:
    cmds:
      - echo "Compilando el proyecto..."
      - go build -o ./bin/Asistente_Ruta_Camioneros ./src/main/*.go
      - go build -o ./bin/Asistente_Ruta_Camioneros ./src/route/*.go
      - echo "Listo."

  clean:
    cmds:
      - echo "Limpiando archivos binarios..."
      - rm -rf ./bin/*
      - echo "Listo."

  run: 
    depends:
      - build
    cmds:
      - echo "Ejecutando el proyecto..."
      - go run ./src/main/main.go
      #- ./bin/Asistente_Ruta_Camioneros

  test:
    cmds:
      - echo "Ejecutando tests..."
      - go test ./test/...
      - echo "Listo."

  check:
    cmds:
      - echo "Comprobando sintaxis..."
      - go vet ./...
      - echo "Listo."

  # help:
  #   cmds:
  #     - echo "task check: Comprueba la sintaxis de la entidad o entidades programadas."
  #     - echo "task build: Compila el proyecto."
  #     - echo "task clean: Limpia los archivos binarios."
  #     - echo "task run: Ejecuta el proyecto."
  #     - echo "task test: Ejecuta los tests."
