version: '3'

tasks:
  build:
    cmds:
      - echo "Compilando el proyecto..."
      - go build -o ./bin/Asistente_Ruta_Camioneros ./src/route/*.go
      - echo "Listo."

  clean:
    cmds:
      - echo "Limpiando archivos binarios..."
      - rm -rf ./bin/*
      - echo "Listo."

  run: 
    depends:
      - build
    cmds:
      - echo "Ejecutando el proyecto..."
      - ./bin/Asistente_Ruta_Camioneros

  test:
    cmds:
      - echo "Ejecutando tests..."
      - go test ./test/...
      - echo "Listo."

  check:
    cmds:
      - echo "Comprobando sintaxis..."
      - go vet ./...
      - echo "Listo."

