name: Test CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.20', '1.21']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install task
      run: |
        curl -sL https://taskfile.dev/install.sh | sh
        sudo mv ./task /usr/local/bin/task
        task --version

    - name: Run tests
      run: task test

    - name: Display Go version
      run: go version

